### REGISTER Request
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### LOGIN Request
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### GET USER PROFILE
GET http://localhost:8080/user/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsZXhAZW1haWwuY29tIiwidWlkIjoiOGY1ZWE3NDQtZTM3Yi00MTIxLTkxNTctZmU5YjVjMDgzZTA0Iiwicm9sZSI6IlZJU0lUT1IiLCJleHAiOjE3NDk4MTQzMjd9.6KT86w774Vr9sm6UYpKB5O9WXghihN2Ga9wkkGqK2Bk

{
}


### GET ALL USERS
GET http://localhost:8080/user/home
content-type: application/json


