### REGISTER Request
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### LOGIN Request
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### GET USER PROFILE
GET http://localhost:8080/user/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsZXhAZW1haWwuY29tIiwidWlkIjoiM2VmNGFhM2UtMTZlYS00MGY4LTg2NDEtNjg1OWU0OTI0ZjRiIiwicm9sZSI6IlZJU0lUT1IiLCJleHAiOjE3NDk4MTI2OTF9.jSXN5HXtRNbPJfj0HRzbhnRMN5o4JY82Jyn6F6Y5GxE

{
}


### GET ALL USERS
GET http://localhost:8080/user/home
content-type: application/json


