### REGISTER Request
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### LOGIN Request
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### GET USER PROFILE
GET http://localhost:8080/user/me
content-type: application/json
Authorization: Bearer

{
}


### GET ALL USERS
GET http://localhost:8080/user/home
content-type: application/json


